/** Theme Config (Name, Description, Background Color, High Contrast Font Color) */
export const themes = [
  {
    name: "light",
    description: "Bright Light Theme, Clean And Fresh For Daily Use",
    backgroundColor: "#f9fafb",
    fontColor: "#111827",
  },
  {
    name: "dark",
    description: "Deep Dark Theme, Lower Eye Strain For Night Use",
    backgroundColor: "#111827",
    fontColor: "#f9fafb",
  },
  {
    name: "abyss",
    description: "Abyss Theme, Deep Purple Tone With Mysterious Atmosphere",
    backgroundColor: "#07031a",
    fontColor: "#c4b5fd",
  },
  {
    name: "valentine",
    description: "Valentine Theme, Romantic Pink Palette Filled With Love",
    backgroundColor: "#fef2f2",
    fontColor: "#9f1239",
  },
  {
    name: "lemonade",
    description: "Lemonade Theme, Fresh Lemon Yellow And Cheerful",
    backgroundColor: "#fefce8",
    fontColor: "#92400e",
  },
  {
    name: "cupcake",
    description: "Cupcake Theme, Soft Sweet Colors With Cozy Feel",
    backgroundColor: "#fdf2f8",
    fontColor: "#2d3748",
  },
  {
    name: "bumblebee",
    description: "Bumblebee Theme, Bold Yellow And Black With Energy",
    backgroundColor: "#fef3c7",
    fontColor: "#2d3748",
  },
  {
    name: "emerald",
    description: "Emerald Theme, Rich Greens For An Elegant Look",
    backgroundColor: "#ecfdf5",
    fontColor: "#065f46",
  },
  {
    name: "corporate",
    description: "Corporate Theme, Steady Professional Palette For Work",
    backgroundColor: "#f8fafc",
    fontColor: "#1e293b",
  },
  {
    name: "synthwave",
    description: "Synthwave Theme, Retro Electronic Style With Neon",
    backgroundColor: "#0f172a",
    fontColor: "#f8fafc",
  },
  {
    name: "retro",
    description: "Retro Theme, Classic Palette Evoking Nostalgia",
    backgroundColor: "#faf6ed",
    fontColor: "#4b5563",
  },
  {
    name: "cyberpunk",
    description: "Cyberpunk Theme, Futuristic Tech Style With Neon Cool Tones",
    backgroundColor: "#080208",
    fontColor: "#fef7fb",
  },
  {
    name: "halloween",
    description: "Halloween Theme, Dark Mood With Pumpkin Orange Accents",
    backgroundColor: "#1f2937",
    fontColor: "#fcd34d",
  },
  {
    name: "garden",
    description: "Garden Theme, Fresh Floral Greens For A Natural Feel",
    backgroundColor: "#f0fdf4",
    fontColor: "#065f46",
  },
  {
    name: "forest",
    description: "Forest Theme, Deep Greens Close To Outdoor Atmosphere",
    backgroundColor: "#064e3b",
    fontColor: "#d1fae5",
  },
  {
    name: "aqua",
    description: "Aqua Theme, Clear Blue Green Tones For Cool Breeze",
    backgroundColor: "#e0f2fe",
    fontColor: "#0369a1",
  },
  {
    name: "lofi",
    description: "Lofi Theme, Soft Warm Colors For Relaxed Vibes",
    backgroundColor: "#f5f5f4",
    fontColor: "#4b5563",
  },
  {
    name: "pastel",
    description: "Pastel Theme, Gentle Light Hues With Warmth",
    backgroundColor: "#f9fafb",
    fontColor: "#374151",
  },
  {
    name: "fantasy",
    description: "Fantasy Theme, Dreamy Colors Full Of Imagination",
    backgroundColor: "#fcf1f7",
    fontColor: "#831843",
  },
  {
    name: "wireframe",
    description: "Wireframe Theme, Minimal Lines With Tech Feel",
    backgroundColor: "#ffffff",
    fontColor: "#000000",
  },
  {
    name: "black",
    description: "Black Theme, Pure Dark Experience With Simplicity",
    backgroundColor: "#000000",
    fontColor: "#ffffff",
  },
  {
    name: "luxury",
    description: "Luxury Theme, Premium Gold Brown Palette Showing Quality",
    backgroundColor: "#faf5ff",
    fontColor: "#5b21b6",
  },
  {
    name: "dracula",
    description: "Dracula Theme, Dark And Crimson Tones With Mystery",
    backgroundColor: "#282a36",
    fontColor: "#f8f8f2",
  },
  {
    name: "cmyk",
    description: "CMYK Theme, Print Primary Colors With Clear Layers",
    backgroundColor: "#ffffff",
    fontColor: "#000000",
  },
  {
    name: "autumn",
    description: "Autumn Theme, Warm Orange Red Palette With Fall Feeling",
    backgroundColor: "#fef3c7",
    fontColor: "#92400e",
  },
  {
    name: "business",
    description: "Business Theme, Lean Professional Colors For Work Scenes",
    backgroundColor: "#f9fafb",
    fontColor: "#1e293b",
  },
  {
    name: "acid",
    description: "Acid Theme, High Saturation Clash With Bold Personality",
    backgroundColor: "#0d0221",
    fontColor: "#f0abfc",
  },
  {
    name: "night",
    description: "Night Theme, Deep Blue Black With Calm Mood",
    backgroundColor: "#0f172a",
    fontColor: "#e0e7ff",
  },
  {
    name: "coffee",
    description: "Coffee Theme, Warm Brown Tones With Cozy Aroma",
    backgroundColor: "#f8f5f0",
    fontColor: "#442d26",
  },
  {
    name: "winter",
    description: "Winter Theme, Snow White Cool Palette Quiet And Pure",
    backgroundColor: "#f8fafc",
    fontColor: "#0f172a",
  },
  {
    name: "dim",
    description: "Dim Theme, Low Brightness Colors Soft And Gentle",
    backgroundColor: "#1e293b",
    fontColor: "#e2e8f0",
  },
  {
    name: "nord",
    description: "Nord Theme, Minimal Cool Palette With Fresh Nordic Style",
    backgroundColor: "#f5f5f5",
    fontColor: "#2e3440",
  },
  {
    name: "sunset",
    description: "Sunset Theme, Orange Pink Glow Creating Romantic Atmosphere",
    backgroundColor: "#fef7fb",
    fontColor: "#c026d3",
  },
  {
    name: "caramellatte",
    description: "Caramellatte Theme, Warm Brown Sweet Tones With Comfort",
    backgroundColor: "#faf6ed",
    fontColor: "#78350f",
  },
  {
    name: "silk",
    description: "Silk Theme, Smooth Delicate Shades With Premium Texture",
    backgroundColor: "#fcf1f7",
    fontColor: "#701a75",
  },
];
