/** 主题配置（包含名称、描述、背景色、高对比字体色） */
export const themes = [
  {
    name: "light",
    description: "明亮浅色主题，简洁清爽，适合日常使用",
    backgroundColor: "#f9fafb",
    fontColor: "#111827",
  },
  {
    name: "dark",
    description: "深色暗黑主题，降低视觉疲劳，适合夜间使用",
    backgroundColor: "#111827",
    fontColor: "#f9fafb",
  },
  {
    name: "abyss",
    description: "深渊主题，深邃暗紫色调，神秘浩瀚",
    backgroundColor: "#07031a",
    fontColor: "#c4b5fd",
  },
  {
    name: "valentine",
    description: "情人节主题，浪漫粉红包调，充满爱意氛围",
    backgroundColor: "#fef2f2",
    fontColor: "#9f1239",
  },
  {
    name: "lemonade",
    description: "柠檬水主题，清新柠檬黄，明快清爽",
    backgroundColor: "#fefce8",
    fontColor: "#92400e",
  },
  {
    name: "cupcake",
    description: "纸杯蛋糕主题，柔和甜美色调，充满治愈感",
    backgroundColor: "#fdf2f8",
    fontColor: "#2d3748",
  },
  {
    name: "bumblebee",
    description: "大黄蜂主题，黄黑撞色设计，活力十足",
    backgroundColor: "#fef3c7",
    fontColor: "#2d3748",
  },
  {
    name: "emerald",
    description: "祖母绿主题，深邃绿色系，彰显高贵质感",
    backgroundColor: "#ecfdf5",
    fontColor: "#065f46",
  },
  {
    name: "corporate",
    description: "企业商务主题，沉稳专业色调，适合办公场景",
    backgroundColor: "#f8fafc",
    fontColor: "#1e293b",
  },
  {
    name: "synthwave",
    description: "合成波主题，复古电子风格，霓虹色彩搭配",
    backgroundColor: "#0f172a",
    fontColor: "#f8fafc",
  },
  {
    name: "retro",
    description: "复古怀旧主题，复刻经典色调，唤起年代感",
    backgroundColor: "#faf6ed",
    fontColor: "#4b5563",
  },
  {
    name: "cyberpunk",
    description: "赛博朋克主题，未来科技风格，霓虹冷色调",
    backgroundColor: "#080208",
    fontColor: "#fef7fb",
  },
  {
    name: "halloween",
    description: "万圣节主题，神秘暗黑风格，南瓜橙黑配色",
    backgroundColor: "#1f2937",
    fontColor: "#fcd34d",
  },
  {
    name: "garden",
    description: "花园主题，清新花草色调，自然舒适感",
    backgroundColor: "#f0fdf4",
    fontColor: "#065f46",
  },
  {
    name: "forest",
    description: "森林主题，深绿自然色系，贴近户外氛围",
    backgroundColor: "#064e3b",
    fontColor: "#d1fae5",
  },
  {
    name: "aqua",
    description: "水蓝主题，清澈蓝绿色调，清爽通透",
    backgroundColor: "#e0f2fe",
    fontColor: "#0369a1",
  },
  {
    name: "lofi",
    description: "低保真主题，柔和暖色调，慵懒放松氛围",
    backgroundColor: "#f5f5f4",
    fontColor: "#4b5563",
  },
  {
    name: "pastel",
    description: "马卡龙主题，浅淡柔和色系，温柔治愈",
    backgroundColor: "#f9fafb",
    fontColor: "#374151",
  },
  {
    name: "fantasy",
    description: "奇幻主题，梦幻色彩搭配，充满想象力",
    backgroundColor: "#fcf1f7",
    fontColor: "#831843",
  },
  {
    name: "wireframe",
    description: "线框主题，简约线条风格，科技感十足",
    backgroundColor: "#ffffff",
    fontColor: "#000000",
  },
  {
    name: "black",
    description: "纯黑主题，极致深色体验，简约纯粹",
    backgroundColor: "#000000",
    fontColor: "#ffffff",
  },
  {
    name: "luxury",
    description: "奢华主题，高端金棕色调，彰显品质感",
    backgroundColor: "#faf5ff",
    fontColor: "#5b21b6",
  },
  {
    name: "dracula",
    description: "德古拉主题，暗黑血红色调，神秘冷酷",
    backgroundColor: "#282a36",
    fontColor: "#f8f8f2",
  },
  {
    name: "cmyk",
    description: "CMYK主题，印刷三原色搭配，鲜明有层次",
    backgroundColor: "#ffffff",
    fontColor: "#000000",
  },
  {
    name: "autumn",
    description: "秋日主题，暖黄橙红配色，浓郁秋意",
    backgroundColor: "#fef3c7",
    fontColor: "#92400e",
  },
  {
    name: "business",
    description: "商务主题，干练专业色调，适合工作场景",
    backgroundColor: "#f9fafb",
    fontColor: "#1e293b",
  },
  {
    name: "acid",
    description: "酸性主题，高饱和撞色，个性前卫",
    backgroundColor: "#0d0221",
    fontColor: "#f0abfc",
  },
  {
    name: "night",
    description: "夜色主题，深邃蓝黑配色，静谧沉稳",
    backgroundColor: "#0f172a",
    fontColor: "#e0e7ff",
  },
  {
    name: "coffee",
    description: "咖啡主题，深棕暖色调，温馨舒适",
    backgroundColor: "#f8f5f0",
    fontColor: "#442d26",
  },
  {
    name: "winter",
    description: "冬日主题，雪白冷色调，纯净静谧",
    backgroundColor: "#f8fafc",
    fontColor: "#0f172a",
  },
  {
    name: "dim",
    description: "微光主题，低亮度色调，柔和不刺眼",
    backgroundColor: "#1e293b",
    fontColor: "#e2e8f0",
  },
  {
    name: "nord",
    description: "北欧主题，简约冷色调，清新自然",
    backgroundColor: "#f5f5f5",
    fontColor: "#2e3440",
  },
  {
    name: "sunset",
    description: "日落主题，橙红暖色调，浪漫氛围感",
    backgroundColor: "#fef7fb",
    fontColor: "#c026d3",
  },
  {
    name: "caramellatte",
    description: "焦糖拿铁主题，暖棕甜色调，温馨治愈",
    backgroundColor: "#faf6ed",
    fontColor: "#78350f",
  },
  {
    name: "silk",
    description: "丝绸主题，柔滑细腻色调，高级质感",
    backgroundColor: "#fcf1f7",
    fontColor: "#701a75",
  },
];
